/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javafoodapp.view.form;

import javafoodapp.controller.MenuMakananController;
import javafoodapp.model.MenuMakanan;
import javafoodapp.swing.MyTextField;
import javafoodapp.view.pages.BahanBakuPage;
import javafoodapp.view.pages.MenuMakananPage;

import javax.swing.*;

/**
 *
 * @author imannrhman
 */
public class MenuMakanForm extends javax.swing.JPanel {

    /**
     * Creates new form MenuMakanForm
     */
    JPanel mainPanel;
    MenuMakananController controller;
    MenuMakanan menuMakanan;
    public MenuMakanForm(JPanel panel, MenuMakanan menuMakanan) {
        initComponents();
        controller = new MenuMakananController(this);
        mainPanel = panel;
        this.menuMakanan = menuMakanan;
        controller.getBahan();
        controller.checkForm(menuMakanan);
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JList<String> getListBahan() {
        return listBahan;
    }


    public MyTextField getMenuField() {
        return menuField;
    }

    public MyTextField getHargaField() {
        return hargaField;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder2 = new javafoodapp.swing.PanelBorder();
        manuMakananText = new javax.swing.JLabel();
        save2 = new javafoodapp.swing.Button();
        cancel2 = new javafoodapp.swing.Button();
        menuField = new javafoodapp.swing.MyTextField();
        title2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listBahan = new javax.swing.JList<>();
        listBahanText = new javax.swing.JLabel();
        listBahanText1 = new javax.swing.JLabel();
        hargaField = new javafoodapp.swing.MyTextField();

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder2.setPreferredSize(new java.awt.Dimension(759, 500));

        manuMakananText.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        manuMakananText.setForeground(new java.awt.Color(127, 127, 127));
        manuMakananText.setText("Menu Makanan");

        save2.setBackground(new java.awt.Color(7, 164, 121));
        save2.setForeground(new java.awt.Color(255, 255, 255));
        save2.setText("SAVE");
        save2.setToolTipText("");
        save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        cancel2.setBackground(new java.awt.Color(230, 44, 44));
        cancel2.setForeground(new java.awt.Color(255, 255, 255));
        cancel2.setText("CANCEL");
        cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel2ActionPerformed(evt);
            }
        });

        menuField.setBackground(new java.awt.Color(233, 233, 233));
        menuField.setForeground(new java.awt.Color(51, 51, 51));

        title2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        title2.setForeground(new java.awt.Color(127, 127, 127));
        title2.setText("Form Menu Makanan");

        listBahan.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listBahan);

        listBahanText.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        listBahanText.setForeground(new java.awt.Color(127, 127, 127));
        listBahanText.setText("Harga");

        listBahanText1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        listBahanText1.setForeground(new java.awt.Color(127, 127, 127));
        listBahanText1.setText("Bahan");

        hargaField.setBackground(new java.awt.Color(233, 233, 233));
        hargaField.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(save2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBorder2Layout.createSequentialGroup()
                                .addComponent(listBahanText1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addGroup(panelBorder2Layout.createSequentialGroup()
                                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelBorder2Layout.createSequentialGroup()
                                        .addComponent(menuField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(38, 38, 38))
                                    .addGroup(panelBorder2Layout.createSequentialGroup()
                                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(title2)
                                            .addComponent(manuMakananText))
                                        .addGap(75, 75, 75)))
                                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelBorder2Layout.createSequentialGroup()
                                        .addComponent(listBahanText)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panelBorder2Layout.createSequentialGroup()
                                        .addComponent(hargaField, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                        .addGap(74, 74, 74)))))))
                .addGap(22, 22, 22))
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(title2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manuMakananText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listBahanText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(listBahanText1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       if (menuMakanan != null ) {
           controller.editData(menuMakanan.getKodeMenu());
       } else {
           controller.insertData();
       }
    }//GEN-LAST:event_saveActionPerformed

    private void cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel2ActionPerformed
        mainPanel.removeAll();
        mainPanel.add(new MenuMakananPage(mainPanel));
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_cancel2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javafoodapp.swing.Button cancel2;
    private javafoodapp.swing.MyTextField hargaField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listBahan;
    private javax.swing.JLabel listBahanText;
    private javax.swing.JLabel listBahanText1;
    private javax.swing.JLabel manuMakananText;
    private javafoodapp.swing.MyTextField menuField;
    private javafoodapp.swing.PanelBorder panelBorder2;
    private javafoodapp.swing.Button save2;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
