/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javafoodapp.view.form;

import javafoodapp.controller.TransaksiController;
import javafoodapp.swing.Table;
import javafoodapp.view.pages.MenuMakananPage;
import javafoodapp.view.pages.TransaksiPage;

import javax.swing.*;

/**
 *
 * @author imannrhman
 */
public class TransaksiForm extends javax.swing.JPanel {

    /**
     * Creates new form TransaksiForm
     */
    JPanel mainPanel;
    TransaksiController controller;
    public TransaksiForm(JPanel panel) {
        initComponents();
        mainPanel = panel;
        controller = new TransaksiController(this);
        controller.setInputTable();
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public Table getTableInput() {
        return tableInput;
    }

    public JButton getTambahDataTable() {
        return tambahDataTable;
    }

    public JButton getHapusDataTable() {
        return hapusDataTable;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder2 = new javafoodapp.swing.PanelBorder();
        tambah = new javafoodapp.swing.Button();
        cancel = new javafoodapp.swing.Button();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInput = new javafoodapp.swing.Table();
        tambahDataTable = new javax.swing.JButton();
        hapusDataTable = new javax.swing.JButton();

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder2.setPreferredSize(new java.awt.Dimension(759, 500));

        tambah.setBackground(new java.awt.Color(7, 164, 121));
        tambah.setForeground(new java.awt.Color(255, 255, 255));
        tambah.setText("SAVE");
        tambah.setToolTipText("");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        cancel.setBackground(new java.awt.Color(230, 44, 44));
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(127, 127, 127));
        title.setText("Form Transaksi");

        tableInput.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "", null}
            },
            new String [] {
                "No", "Nama Barang", "Stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableInput.setEnabled(false);
        jScrollPane1.setViewportView(tableInput);

        tambahDataTable.setText("Tambah");
        tambahDataTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                tambahDataTableComponentMoved(evt);
            }
        });
        tambahDataTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahDataTableActionPerformed(evt);
            }
        });

        hapusDataTable.setText("Hapus");

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addComponent(title)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                            .addGroup(panelBorder2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tambahDataTable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hapusDataTable)))
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahDataTable)
                    .addComponent(hapusDataTable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        controller.tambahTransaksi();
    }//GEN-LAST:event_tambahActionPerformed

    private void tambahDataTableComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tambahDataTableComponentMoved

    }//GEN-LAST:event_tambahDataTableComponentMoved

    private void tambahDataTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahDataTableActionPerformed
        controller.tambahTransaksi();
    }//GEN-LAST:event_tambahDataTableActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        mainPanel.removeAll();
        mainPanel.add(new TransaksiPage(mainPanel));
        mainPanel.repaint();
        mainPanel.revalidate();

    }//GEN-LAST:event_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javafoodapp.swing.Button cancel;
    private javax.swing.JButton hapusDataTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javafoodapp.swing.PanelBorder panelBorder2;
    private javafoodapp.swing.Table tableInput;
    private javafoodapp.swing.Button tambah;
    private javax.swing.JButton tambahDataTable;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
