/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package javafoodapp.view.old;

//import com.sun.jdi.connect.spi.Connection;
import javafoodapp.database.ConnectionDatabase;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;

// Saya ngerubah bagian koneksi ke databasenya man
// connection jadi koneksi
//getConnection jadi get koneksi

/**
 *
 * @author user
 */
public class kelolaBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form showBarang
     */
    public kelolaBarang() {
        initComponents();
        tampil_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodypanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        uploadbarang = new javax.swing.JButton();
        showbarang = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panel_showbarang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_barang = new javax.swing.JTable();
        editbarang = new javax.swing.JButton();
        deletebrg = new javax.swing.JButton();
        panel_uploadbarang = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idbarang_field = new javax.swing.JTextField();
        nama_field = new javax.swing.JTextField();
        kategori_field = new javax.swing.JTextField();
        harga_field = new javax.swing.JTextField();
        stok_field = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        panel_editbarang = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        idbarang_edit = new javax.swing.JTextField();
        nama_edit = new javax.swing.JTextField();
        kategori_edit = new javax.swing.JTextField();
        harga_edit = new javax.swing.JTextField();
        stok_edit = new javax.swing.JTextField();
        editbtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Barang");
        setPreferredSize(new java.awt.Dimension(785, 530));

        bodypanel.setBackground(new java.awt.Color(255, 99, 71));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/brg1.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Reem Kufi", 1, 14)); // NOI18N
        jLabel1.setText("Barang");

        uploadbarang.setText("Upload Barang");
        uploadbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadbarangActionPerformed(evt);
            }
        });

        showbarang.setText("Show Barang");
        showbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uploadbarang)
                    .addComponent(showbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(showbarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uploadbarang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel2.setPreferredSize(new java.awt.Dimension(756, 499));
        jPanel2.setLayout(new java.awt.CardLayout());

        panel_showbarang.setBackground(new java.awt.Color(247, 197, 100));
        panel_showbarang.setPreferredSize(new java.awt.Dimension(752, 495));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Data Barang");

        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Id Barang", "Nama", "Kategori", "Harga", "Stok"
            }
        ));
        tabel_barang.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabel_barangAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabel_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_barangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_barang);

        editbarang.setText("Edit Barang");
        editbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbarangActionPerformed(evt);
            }
        });

        deletebrg.setText("Hapus Barang");
        deletebrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebrgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_showbarangLayout = new javax.swing.GroupLayout(panel_showbarang);
        panel_showbarang.setLayout(panel_showbarangLayout);
        panel_showbarangLayout.setHorizontalGroup(
            panel_showbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_showbarangLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(200, 200, 200))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_showbarangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(490, 490, 490))
            .addGroup(panel_showbarangLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(editbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deletebrg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_showbarangLayout.setVerticalGroup(
            panel_showbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_showbarangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262)
                .addGroup(panel_showbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editbarang)
                    .addComponent(deletebrg))
                .addGap(32, 32, 32))
        );

        jPanel2.add(panel_showbarang, "card2");

        panel_uploadbarang.setBackground(new java.awt.Color(255, 204, 153));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Upload Barang");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ID Barang          :");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nama Barang   :");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Kategori             :");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Harga                 :");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Stok                    :");

        idbarang_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbarang_fieldActionPerformed(evt);
            }
        });

        addbtn.setText("Submit");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_uploadbarangLayout = new javax.swing.GroupLayout(panel_uploadbarang);
        panel_uploadbarang.setLayout(panel_uploadbarangLayout);
        panel_uploadbarangLayout.setHorizontalGroup(
            panel_uploadbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_uploadbarangLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(panel_uploadbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(panel_uploadbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama_field)
                    .addComponent(idbarang_field)
                    .addComponent(stok_field, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(harga_field)
                    .addComponent(kategori_field))
                .addGap(198, 198, 198))
            .addGroup(panel_uploadbarangLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_uploadbarangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addbtn)
                .addGap(77, 77, 77))
        );
        panel_uploadbarangLayout.setVerticalGroup(
            panel_uploadbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_uploadbarangLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addGap(39, 39, 39)
                .addGroup(panel_uploadbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_uploadbarangLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_uploadbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(nama_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_uploadbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kategori_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_uploadbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(harga_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_uploadbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(stok_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(idbarang_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(addbtn)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jPanel2.add(panel_uploadbarang, "card3");

        panel_editbarang.setBackground(new java.awt.Color(255, 255, 102));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Edit Barang");

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("ID Barang          :");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Nama Barang   :");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Kategori             :");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Harga                 :");

        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Stok                    :");

        idbarang_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbarang_editActionPerformed(evt);
            }
        });

        editbtn.setText("Submit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_editbarangLayout = new javax.swing.GroupLayout(panel_editbarang);
        panel_editbarang.setLayout(panel_editbarangLayout);
        panel_editbarangLayout.setHorizontalGroup(
            panel_editbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_editbarangLayout.createSequentialGroup()
                .addGroup(panel_editbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_editbarangLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(panel_editbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(panel_editbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nama_edit, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kategori_edit, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(harga_edit, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stok_edit, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idbarang_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_editbarangLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel11))
                    .addGroup(panel_editbarangLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(editbtn)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        panel_editbarangLayout.setVerticalGroup(
            panel_editbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_editbarangLayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(35, 35, 35)
                .addGroup(panel_editbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_editbarangLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_editbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(nama_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_editbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kategori_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_editbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(harga_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_editbarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(stok_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(idbarang_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(editbtn)
                .addGap(128, 128, 128))
        );

        jPanel2.add(panel_editbarang, "card4");

        javax.swing.GroupLayout bodypanelLayout = new javax.swing.GroupLayout(bodypanel);
        bodypanel.setLayout(bodypanelLayout);
        bodypanelLayout.setHorizontalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bodypanelLayout.setVerticalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadbarangActionPerformed
        // TODO add your handling code here:
        //remove panel sebelumnya
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        //add panel setelahnya
        jPanel2.add(panel_uploadbarang);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_uploadbarangActionPerformed

    private void editbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbarangActionPerformed
        // TODO add your handling code here:
        //remove panel sebelumnya
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        //add panel setelahnya
        jPanel2.add(panel_editbarang);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_editbarangActionPerformed

    private void showbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbarangActionPerformed
        // TODO add your handling code here:
        
        //remove panel sebelumnya
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        //add panel setelahnya
        jPanel2.add(panel_showbarang);
        jPanel2.repaint();
        jPanel2.revalidate();
    }//GEN-LAST:event_showbarangActionPerformed

    private void tabel_barangAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabel_barangAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_barangAncestorAdded

    private void idbarang_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbarang_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbarang_fieldActionPerformed

    private void tabel_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_barangMouseClicked
        // TODO add your handling code here:
        int baris = tabel_barang.rowAtPoint(evt.getPoint());
        
        String idbarang = tabel_barang.getValueAt(baris, 1).toString();
        idbarang_edit.setText(idbarang);
        String nama = tabel_barang.getValueAt(baris, 2).toString();
        nama_edit.setText(nama);
        String kategori = tabel_barang.getValueAt(baris, 3).toString();
        kategori_edit.setText(kategori);
        String harga = tabel_barang.getValueAt(baris, 4).toString();
        harga_edit.setText(harga);
        String stok = tabel_barang.getValueAt(baris, 5).toString();
        stok_edit.setText(stok);
    }//GEN-LAST:event_tabel_barangMouseClicked

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        String idb = idbarang_field.getText();
        String nm = nama_field.getText();
        String kt = kategori_field.getText();
        String hg = harga_field.getText();
        String st = stok_field.getText();

        if(nm.equals("")){
            JOptionPane.showMessageDialog(null, "Isi nama dulu gaes");
        } else if (st.equals("")){
            JOptionPane.showMessageDialog(null, "Isi stok dulu");
        } else {
            try {
            String Q = "INSERT INTO bahan_baku (id, nama_bahan, kategori_barang, harga, stok) VALUES ('"+idb+"','"+nm+"','"+kt+"','"+hg+"','"+st+"')";
            java.sql.Connection vcomm = (Connection)ConnectionDatabase.getConnection();
            java.sql.PreparedStatement s = vcomm.prepareStatement(Q);
            s.execute();
            JOptionPane.showMessageDialog(null, "Tambah data berhasil");
                    
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, "Tambah data gagal");
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            tampil_table();//autorefresh
            
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void idbarang_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbarang_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbarang_editActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        String idb = idbarang_edit.getText();
        String nm = nama_edit.getText();
        String kt = kategori_edit.getText();
        String hg = harga_edit.getText();
        String st = stok_edit.getText();
        try {
        
        String SQL = "UPDATE bahan_baku set id= '"+idb+"',nama_bahan= '"+nm+"' ,kategori_barang= '"+kt+"' ,harga= '"+hg+"' ,stok= '"+st+"' WHERE id='"+idb+"' ";
        Connection Vconn = (Connection)ConnectionDatabase.getConnection();
        java.sql.PreparedStatement pst = Vconn.prepareStatement(SQL);
        pst.execute();
        JOptionPane.showMessageDialog(null, "Data telah dirubah");
        tampil_table();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "eror" +e.getMessage());
        }
        
    }//GEN-LAST:event_editbtnActionPerformed

    private void deletebrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebrgActionPerformed
        // TODO add your handling code here:
        String idb = idbarang_edit.getText();
//        String nm = nama_field.getText();
//        String kt = kategori_field.getText();
//        String hg = harga_field.getText();
//        String st = stok_field.getText();
        
        try {
            //query
            String querydel = "Delete from bahan_baku where id='"+idb+"'";
            //koneksi
            Connection Vconn = (Connection)ConnectionDatabase.getConnection();
            // statement
            java.sql.PreparedStatement stm = Vconn.prepareStatement(querydel);
            // eksekusi querydel
            stm.execute();
            //notif
            JOptionPane.showMessageDialog(null, "Hapus data berhasil");
            tampil_table();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "eror" +e.getMessage());
        }
    }//GEN-LAST:event_deletebrgActionPerformed

    private void tampil_table(){
        //membuat ibjek model pada tabel
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("No");
        tb.addColumn("Id Barang");
        tb.addColumn("Nama");
        tb.addColumn("Kategori");
        tb.addColumn("Harga");
        tb.addColumn("Stok");
        
        try {
            int counter = 1;
            //Query
            String query = "SELECT * FROM bahan_baku";
            
            //fungsi koneksi
//            java.sql.Connection vcomm = (java.sql.Connection)(Connection)ConnectionDatabase.getConnection();
            java.sql.Connection vconn = (Connection)ConnectionDatabase.getConnection();
            
            //kirim parameter java ke sql
            java.sql.Statement s = vconn.createStatement();
            //' excute
            java.sql.ResultSet r = s.executeQuery(query);
            
            //show data with lopping
            while (r.next()) {
              tb.addRow(new Object[]{
                  counter++,r.getString(1),r.getString(2),r.getString(3),r.getInt(4),r.getInt(5)
              });
                
            }
            tabel_barang.setModel(tb);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "eror" +e.getMessage());

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JPanel bodypanel;
    private javax.swing.JButton deletebrg;
    private javax.swing.JButton editbarang;
    private javax.swing.JButton editbtn;
    private javax.swing.JTextField harga_edit;
    private javax.swing.JTextField harga_field;
    private javax.swing.JTextField idbarang_edit;
    private javax.swing.JTextField idbarang_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kategori_edit;
    private javax.swing.JTextField kategori_field;
    private javax.swing.JTextField nama_edit;
    private javax.swing.JTextField nama_field;
    private javax.swing.JPanel panel_editbarang;
    private javax.swing.JPanel panel_showbarang;
    private javax.swing.JPanel panel_uploadbarang;
    private javax.swing.JButton showbarang;
    private javax.swing.JTextField stok_edit;
    private javax.swing.JTextField stok_field;
    private javax.swing.JTable tabel_barang;
    private javax.swing.JButton uploadbarang;
    // End of variables declaration//GEN-END:variables
}
